version: '3.8'

# source https://github.com/minekube/gate/blob/master/.web/docs/guide/otel/self-hosted/jaeger-config/docker-compose.yml
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      # OTLP receiver ports (gRPC and HTTP)
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
      # Jaeger UI
      - '16686:16686' # Jaeger Query UI
